Trying to give it permissions to do all Cognito authentication.
AccessDeniedException: User: arn:aws:sts::420836428571:assumed-role/payment-driver-staging-LoginRole-1U3GPPKFVWK1G/payment-driver-staging-Login-1JS6VPRUQ52U6 is not authorized to perform: cognito-idp:AdminRespondToAuthChallenge on resource: arn:aws:cognito-idp:us-east-1:420836428571:userpool/us-east-1_YgXeUisLP